INTERFACE zif_sat_c_cds_api_state
  PUBLIC.
  CONSTANTS add_custom_fields TYPE char30 VALUE 'ADD_CUSTOM_FIELDS' ##NO_TEXT.
  CONSTANTS not_released TYPE char30 VALUE 'NOT_RELEASED' ##NO_TEXT.
  CONSTANTS released TYPE char30 VALUE 'RELEASED' ##NO_TEXT.
ENDINTERFACE.
